#!/usr/bin/env bash
set -eu

ORIG_WD="$(pwd)"

SCRIPT="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

HOOK_DIR="${SCRIPT}-hooks"
cd "${HOOK_DIR}"

HOOKS=($(find . -maxdepth 1 ! -path . | sed 's|^./||' | sort))

cd "${ORIG_WD}"
for hook in ${HOOKS[@]}; do
    ${SCRIPT_DIR}/${HOOK_DIR}/${hook} "$@"
done
