#!/usr/bin/env bash
set -e

# doc: https://git-scm.com/docs/githooks

BACKUP_WD="$(pwd)"

if [ -z "${GIT_DIR}" ]; then
    GIT_DIR="$(git rev-parse --show-toplevel)/.git"
fi

GIT_HOOK_DIR="${GIT_DIR}/hooks"

SCRIPT="$(basename "$0")"
cd "${GIT_HOOK_DIR}"

HOOK_DIR="${SCRIPT}-hooks"
cd "${HOOK_DIR}"

HOOKS=($(find . -maxdepth 1 ! -path . | sed 's|^./||' | sort))

cd "${GIT_DIR}/../"
for hook in ${HOOKS[@]}; do
    ${GIT_HOOK_DIR}/${HOOK_DIR}/${hook} "$@"
done

cd "${BACKUP_WD}"
